### ISSUE TITLE
[BUG] MQTT Requests Not Working

### ISSUE THREAD

**Issue by janstadt** [TheTimeWalker/wallpanel-android#147]
**Describe the bug**
I have properly configured my MQTT broker in wallpanel (i can see the requests from the device in mqtt explorer) but the device is not reacting to the requests.
**To Reproduce**
1. Publish MQTT request from HA:
```
            hold_action:
              action: perform-action
              perform_action: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: wallpanel/parents-tablet/command
                payload: |-
                  {
                    'brightness': 1
                  }
            tap_action:
              action: perform-action
              perform_action: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: wallpanel/parents-tablet/command
                payload: |-
                  {
                    'brightness': 255
                  }
```
2. Device does not respond to brightness command.

**Smartphone (please complete the following information):**
 - Device: Lenovo ThinkSmart
 - OS: Lineage 14 (Android 8)
 - Applicaiton version: latest
