### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aixx1** [TheTimeWalker/wallpanel-android#157]
**Describe the bug**
My device is successfully passing on its sensor data to HA, but HA cannot communicate to the Device.
I can see the messages going through in MQTT Explorer though.

**To Reproduce**
Action I used:
```
action: mqtt.publish
data:
  qos: "1"
  payload: "{\"wake\": true, \"wakeTime\": 180}"
  topic: wallpanel/mywallpanel
  evaluate_payload: true
  retain: false
```

I tried also with `payload: '{"wake": true, "wakeTime": 180}'`, also with different commands like 'brightness' etc. Tried 'topic: wallpanel/mywallpanel', 'topic: wallpanel/mywallpanel/', 'topic: wallpanel/mywallpanel/wake' etc. but the phone doesn't wake up. Tried mostly while the screensaver was active, but also while screen turned off from the power button.

**Smartphone:**
 - Device: Xiaomi Redmi A1
 - OS: Android 12 (Go Edition)
 - Application version 0.12.0 Build 0
