### ISSUE TITLE
[FEATURE] Back and home button

### ISSUE THREAD

**Issue by githubuser2050** [TheTimeWalker/wallpanel-android#170]
As a user I want a back and a home button in order to be able to navigate to the previous webppage or the home dashboard after following links.

**Comment by briodan** [comment]
i added a chips card on all my dashboard pages to allow navigation. This will work on any device weather you are using wallpanel or not. You can hide it via visibility options if you want for certain devices etc.

```
type: custom:mushroom-chips-card
chips:
  - type: menu
  - type: back
```
