### ISSUE TITLE
[BUG] MQTT commands don't work

### ISSUE THREAD

**Issue by briodan** [TheTimeWalker/wallpanel-android#171]
**Describe the bug**
I cant get MQTT commands to work from Home Assistant

**To Reproduce**
I have setup MQTT on the device and I see it publish sensor and connection data to MQTT however MQTT commands do not get picked up by the device

![image](https://github.com/user-attachments/assets/ebc5f3cf-02db-4886-b275-652b8447e150)

this is the command I issue for a reload, note HA translates " to \" when pasted into the GUI and will not allow payload: "{\"reload\": true}", i have also tried payload: "{reload': true}" with no success.

```
action: mqtt.publish
data:
  evaluate_payload: false
  qos: 0
  retain: false
  topic: wallpanel/los1_wp/command
  payload: "{\"reload\": true}"
```

**Smartphone (please complete the following information):**
 - Device: ThinkSmart View
 - OS: Android 8.10 (Lineage OS)
 - Applicaiton version: v0.12.0 build 0
