### ISSUE TITLE
[FEATURE] Return to home link after preset time

### ISSUE THREAD

**Issue by dexonter** [TheTimeWalker/wallpanel-android#76]
**Your feature request. Please describe.**
What is the feature, why is it valuable to the community or application?
As a wallpanel I always interact with the tablet. But it would be fantastic if the tablet could reset to the default view after a configurable amount of time. 

This is a needed feature that increases the UX dramatically (and is found in all top level home displays).

**NOTE**
We get many feature requests, each feature requires community support and also development time. Features that have no community support are not considered.   If you are not contributing to the feature, then the feature may not happen.

**Comment by goopaga** [comment]
Nice suggestion, however I managed this feature with an automation (within Home Assistant in my scenario).

Trigger: when "binary_sensor.my_wall_panel_face_detected" changes from on to off, after xx seconds
Action: if "wallpanel_state_currenturl" is not the default i want, then i publish an MQTT command to change URL passing the default page I need.

In between I dim the screen and set it back to the default brightness afterwards because I don't want to show the refresh while it happens.

My code here below

Cheers



 ```
alias: G5 Panel - GoToDefaultScreen
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.my_wall_panel_face_detected
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 45
condition:
  - condition: not
    conditions:
      - condition: template
        value_template: >-
          {{ is_state('sensor.wallpanel_state_currenturl',
          'http://192.168.0.xx:8123/touch-panel/0') }}
action:
  - service: mqtt.publish
    data:
      topic: wallpanel/mywallpanel/command
      payload: "{\"brightness\": 1}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: mqtt.publish
    data:
      payload: "{\"url\": \"http://192.168.0.xx:8123/touch-panel/0\"}"
      topic: wallpanel/mywallpanel/command
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: wallpanel/mywallpanel/command
      payload: "{\"brightness\": 255}"
mode: single
```
