### ISSUE TITLE
Mqtt command back to wallpanel app

### ISSUE THREAD

**Issue by ice2009** [TheTimeWalker/wallpanel-android#98]
Hello :)

I need help from mqtt. After ringing my doorbell, wallpanel opens the Reolink application. I would need an mqtt command to close reolink application or re-open the wallpanel application with a mqtt command.

This command for reolink application

```
service: mqtt.publish
data:
  topic: wallpanel/mywallpanel/command
  payload: '{"url": "intent:#Intent;launchFlags=0x10000000;component=com.mcu.reolink/com.android.bc.login.WelcomeActivity;end"}'
```
